"""empty message

Revision ID: 093d3585f721
Revises: 7a26535e54b5
Create Date: 2022-06-21 00:10:42.540066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093d3585f721'
down_revision = '7a26535e54b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('monday_start', sa.String(length=120), nullable=True))
    op.add_column('schedule', sa.Column('monday_end', sa.String(length=120), nullable=True))
    op.add_column('schedule', sa.Column('tuesday_start', sa.String(length=120), nullable=True))
    op.add_column('schedule', sa.Column('tuesday_end', sa.String(length=120), nullable=True))
    op.add_column('schedule', sa.Column('wednesday_start', sa.String(length=120), nullable=True))
    op.add_column('schedule', sa.Column('wednesday_end', sa.String(length=120), nullable=True))
    op.add_column('schedule', sa.Column('thursday_start', sa.String(length=120), nullable=True))
    op.add_column('schedule', sa.Column('thursday_end', sa.String(length=120), nullable=True))
    op.add_column('schedule', sa.Column('friday_start', sa.String(length=120), nullable=True))
    op.add_column('schedule', sa.Column('friday_end', sa.String(length=120), nullable=True))
    op.add_column('schedule', sa.Column('saturday_start', sa.String(length=120), nullable=True))
    op.add_column('schedule', sa.Column('saturday_end', sa.String(length=120), nullable=True))
    op.add_column('schedule', sa.Column('sunday_start', sa.String(length=120), nullable=True))
    op.add_column('schedule', sa.Column('sunday_end', sa.String(length=120), nullable=True))
    op.alter_column('schedule', 'full_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_constraint('schedule_day_key', 'schedule', type_='unique')
    op.drop_constraint('schedule_end_time_key', 'schedule', type_='unique')
    op.drop_constraint('schedule_friday_key', 'schedule', type_='unique')
    op.drop_constraint('schedule_monday_key', 'schedule', type_='unique')
    op.drop_constraint('schedule_saturday_key', 'schedule', type_='unique')
    op.drop_constraint('schedule_start_time_key', 'schedule', type_='unique')
    op.drop_constraint('schedule_sunday_key', 'schedule', type_='unique')
    op.drop_constraint('schedule_thursday_key', 'schedule', type_='unique')
    op.drop_constraint('schedule_tuesday_key', 'schedule', type_='unique')
    op.drop_constraint('schedule_wednesday_key', 'schedule', type_='unique')
    op.drop_column('schedule', 'saturday')
    op.drop_column('schedule', 'end_time')
    op.drop_column('schedule', 'monday')
    op.drop_column('schedule', 'start_time')
    op.drop_column('schedule', 'tuesday')
    op.drop_column('schedule', 'wednesday')
    op.drop_column('schedule', 'day')
    op.drop_column('schedule', 'sunday')
    op.drop_column('schedule', 'friday')
    op.drop_column('schedule', 'thursday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('thursday', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('schedule', sa.Column('friday', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('schedule', sa.Column('sunday', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('schedule', sa.Column('day', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('schedule', sa.Column('wednesday', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('schedule', sa.Column('tuesday', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('schedule', sa.Column('start_time', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('schedule', sa.Column('monday', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('schedule', sa.Column('end_time', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('schedule', sa.Column('saturday', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.create_unique_constraint('schedule_wednesday_key', 'schedule', ['wednesday'])
    op.create_unique_constraint('schedule_tuesday_key', 'schedule', ['tuesday'])
    op.create_unique_constraint('schedule_thursday_key', 'schedule', ['thursday'])
    op.create_unique_constraint('schedule_sunday_key', 'schedule', ['sunday'])
    op.create_unique_constraint('schedule_start_time_key', 'schedule', ['start_time'])
    op.create_unique_constraint('schedule_saturday_key', 'schedule', ['saturday'])
    op.create_unique_constraint('schedule_monday_key', 'schedule', ['monday'])
    op.create_unique_constraint('schedule_friday_key', 'schedule', ['friday'])
    op.create_unique_constraint('schedule_end_time_key', 'schedule', ['end_time'])
    op.create_unique_constraint('schedule_day_key', 'schedule', ['day'])
    op.alter_column('schedule', 'full_name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('schedule', 'sunday_end')
    op.drop_column('schedule', 'sunday_start')
    op.drop_column('schedule', 'saturday_end')
    op.drop_column('schedule', 'saturday_start')
    op.drop_column('schedule', 'friday_end')
    op.drop_column('schedule', 'friday_start')
    op.drop_column('schedule', 'thursday_end')
    op.drop_column('schedule', 'thursday_start')
    op.drop_column('schedule', 'wednesday_end')
    op.drop_column('schedule', 'wednesday_start')
    op.drop_column('schedule', 'tuesday_end')
    op.drop_column('schedule', 'tuesday_start')
    op.drop_column('schedule', 'monday_end')
    op.drop_column('schedule', 'monday_start')
    # ### end Alembic commands ###
