"""empty message

Revision ID: b8d8c7a073c2
Revises: 886f239333d2
Create Date: 2022-06-24 22:57:06.298947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d8c7a073c2'
down_revision = '886f239333d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    op.add_column('ghost_car', sa.Column('top_brush', sa.String(length=80), nullable=False))
    op.add_column('ghost_car', sa.Column('wrap_set1', sa.String(length=80), nullable=False))
    op.add_column('ghost_car', sa.Column('wrap_set2', sa.String(length=80), nullable=False))
    op.add_column('ghost_car', sa.Column('second_cta', sa.String(length=80), nullable=False))
    op.drop_constraint('ghost_car_first_topbrush_key', 'ghost_car', type_='unique')
    op.drop_constraint('ghost_car_second_ctas_key', 'ghost_car', type_='unique')
    op.drop_constraint('ghost_car_wrap1_ds_ps_key', 'ghost_car', type_='unique')
    op.drop_constraint('ghost_car_wrap2_ds_ps_key', 'ghost_car', type_='unique')
    op.create_unique_constraint(None, 'ghost_car', ['top_brush'])
    op.create_unique_constraint(None, 'ghost_car', ['wrap_set1'])
    op.create_unique_constraint(None, 'ghost_car', ['wrap_set2'])
    op.create_unique_constraint(None, 'ghost_car', ['second_cta'])
    op.drop_column('ghost_car', 'first_topbrush')
    op.drop_column('ghost_car', 'wrap1_ds_ps')
    op.drop_column('ghost_car', 'wrap2_ds_ps')
    op.drop_column('ghost_car', 'second_ctas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ghost_car', sa.Column('second_ctas', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('ghost_car', sa.Column('wrap2_ds_ps', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('ghost_car', sa.Column('wrap1_ds_ps', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('ghost_car', sa.Column('first_topbrush', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ghost_car', type_='unique')
    op.drop_constraint(None, 'ghost_car', type_='unique')
    op.drop_constraint(None, 'ghost_car', type_='unique')
    op.drop_constraint(None, 'ghost_car', type_='unique')
    op.create_unique_constraint('ghost_car_wrap2_ds_ps_key', 'ghost_car', ['wrap2_ds_ps'])
    op.create_unique_constraint('ghost_car_wrap1_ds_ps_key', 'ghost_car', ['wrap1_ds_ps'])
    op.create_unique_constraint('ghost_car_second_ctas_key', 'ghost_car', ['second_ctas'])
    op.create_unique_constraint('ghost_car_first_topbrush_key', 'ghost_car', ['first_topbrush'])
    op.drop_column('ghost_car', 'second_cta')
    op.drop_column('ghost_car', 'wrap_set2')
    op.drop_column('ghost_car', 'wrap_set1')
    op.drop_column('ghost_car', 'top_brush')
    op.create_table('schedule',
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('monday_start', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('monday_end', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('tuesday_start', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('tuesday_end', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('wednesday_start', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('wednesday_end', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('thursday_start', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('thursday_end', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('friday_start', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('friday_end', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('saturday_start', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('saturday_end', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('sunday_start', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('sunday_end', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('schedule_id', name='schedule_pkey'),
    sa.UniqueConstraint('full_name', name='schedule_full_name_key')
    )
    # ### end Alembic commands ###
